spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.yxesdpzxfdzhumqnqtit
spring.datasource.password=@Uwamwezi33
server.port=${PORT:8080}
server.address=0.0.0.0
spring.jpa.properties.hibernate.connection.url=${spring.datasource.url}
spring.jpa.properties.hibernate.connection.username=${spring.datasource.username}
spring.jpa.properties.hibernate.connection.password=${spring.datasource.password}